### PR TITLE
adding travis stuff

### PR DESCRIPTION
**Pull request by iFlameing**

### CODE REVIEW

**Comment by iFlameing** [comment]
@datakurre can you review this?

**Comment by iFlameing** [comment]
@datakurre Just one problem why I am getting this error 

`Skipping a deployment with the pages provider because this branch is not permitted`

thanks :)

**Comment by iFlameing** [comment]
sorry for the above question. I think I found that my master branch does not contain any travis.yml config that's why it is giving me this error.

can I merge this?

**Comment by datakurre** [comment]
@iFlameing I merged, so we'll see if this works properly on master branch.

**Pull request merged**
